<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
	<UseWindowsForms>true</UseWindowsForms>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputType>Library</OutputType>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\Binaries\</OutputPath>
    <CodeAnalysisRuleSet />
    <NoWarn>1701;1702;MSB3277;CA1416</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>True</Optimize>
    <DebugOptimization>True</DebugOptimization>
    <DebugType>portable</DebugType>
    <OutputPath>..\..\Binaries\</OutputPath>
    <CodeAnalysisRuleSet />
    <NoWarn>1701;1702;MSB3277;CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="NeoAxis.Core">
      <HintPath>..\..\Binaries\NeoAxis.Core.dll</HintPath>
    </Reference>
    <Reference Include="NeoAxis.Core.Editor">
      <HintPath>..\..\Binaries\NeoAxis.Core.Editor.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ExampleEditorCanvasWindow.cs" />
    <Compile Update="ExampleEditorWinFormsWindow.cs" />
  </ItemGroup>
</Project>