<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.neoaxis.AndroidPlayer</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <RootNamespace>NeoAxis.Player.Android</RootNamespace>
    <AssemblyName>NeoAxis.Player.Android</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>ANDROID;DEPLOY;CLIENT;OPENGLES</DefineConstants>
    <DebugType>portable</DebugType>
    <LangVersion>latest</LangVersion>
    <Nullable>annotations</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>C:\_TestAndroid\</OutputPath>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <SupportedOSPlatformVersion>33.0</SupportedOSPlatformVersion>
    <PublishTrimmed>False</PublishTrimmed>
    <RunAOTCompilation>false</RunAOTCompilation>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <NoWarn>
    </NoWarn>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
    <AndroidUseFastDev>False</AndroidUseFastDev>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>
    </NoWarn>
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    <Optimize>False</Optimize>
    <!-- Optional: produce symbols like Debug so stack traces are useful -->
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="libs\arm64-v8a\libNeoAxisCoreNative.so" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Implementation\RestartApp.cs" />
    <Compile Include="Implementation\Engine.cs" />
    <Compile Include="Implementation\FunctionalityAndroid.cs" />
    <Compile Include="Implementation\FunctionalityAndroid.Input.cs" />
    <Compile Include="Implementation\FunctionalityAndroid.Utility.cs" />
    <Compile Include="Implementation\FunctionalityAndroid.Video.cs" />
    <Compile Include="Implementation\LogPlatformFunctionalityAndroid.cs" />
    <Compile Include="Implementation\PlatformSpecificUtilityAndroid.cs" />
    <Compile Include="MainActivity.cs" />
    <Compile Include="Implementation\OpenGLES.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Implementation\Vulkan.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MultiplayerCreateWindow.cs" />
    <Compile Include="Project\Assets\Base\Scripts\SimulationApp.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MainMenuScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MenuWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\OptionsWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\ScenesWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\PlayScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\SplashScreen.cs" />
    <Compile Include="Project\Assets\Base\Scripts\ProjectAssembly.cs" />
    <Compile Include="Project\Assets\Base\UI\Styles\UIStyleEditor.cs" />
    <Compile Include="Project\Assets\Base\UI\Styles\UIStyleSimple.cs" />
    <Compile Include="Project\Assets\Base\UI\Windows\MessageBoxWindow.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\Scripts\ShooterCommon.cs" />
    <Compile Include="Project\Assets\Samples\Simple Game\SimpleGameGUI.cs" />
    <Compile Include="Project\Caches\CSharpScripts\CSharpScripts.cs" />
    <Compile Include="Project\Assets\Base\WindowApp\WindowAppMainForm.cs" />
    <Compile Include="Project\Assets\Samples\Spaceship Game\SpaceshipGameGUI.cs" />
    <Compile Include="Project\Assets\Samples\Platform Game\PlatformGameGUI.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\Scripts\ShooterNetworkLogic.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\UI\ShooterInGameContextScreen.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\UI\ShooterSceneScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MultiplayerJoinWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\BasicSceneScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\EntranceScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\InGameContextScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\AvatarWindow.cs" />
    <Compile Include="Project\Assets\Base\Scripts\ClientUtility.cs" />
    <Compile Include="Project\Assets\Base\Scripts\RunServer.cs" />
    <Compile Include="Project\Assets\Base\Scripts\NetworkLogic.cs" />
    <Compile Include="Project\Assets\Base\Scripts\CloudServiceClient.cs" />
    <Compile Include="Project\Assets\Base\Scripts\SimulationAppClient.cs" />
    <Compile Include="Project\Assets\Base\Scripts\SimulationAppServer.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MatchesWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MatchWindow.cs" />
  </ItemGroup>
  <ItemGroup>
    <AndroidAsset Include="Assets\Project.zip" />
    <AndroidAsset Include="Assets\Project.zip.hash">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AndroidAsset>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="NeoAxis.Core">
      <HintPath>..\..\Binaries\NeoAxis.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AndroidNativeLibrary Include="libs\arm64-v8a\libNeoAxisCoreNative.so">
    <Link>libs\arm64-v8a\libNeoAxisCoreNative.so</Link>
    </AndroidNativeLibrary>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="if EXIST &quot;$(ProjectDir)..\..\Project.csproj&quot; ( if EXIST &quot;$(ProjectDir)..\..\Binaries\NeoAxis.Internal\Platforms\Windows\CommandLineTools\CommandLineTools.exe&quot; ( &quot;$(ProjectDir)..\..\Binaries\NeoAxis.Internal\Platforms\Windows\CommandLineTools\CommandLineTools.exe&quot; -platformProjectPatchWithCopyFiles &quot;$(ProjectDir)NeoAxis.Player.Android.csproj&quot; -baseProject &quot;$(ProjectDir)..\..\Project.csproj&quot; ) )&#xD;&#xA;&#xD;&#xA;set Product=Base\Build\Demo Android.product&#xD;&#xA;rem set Product=Base\Build\Simple Game Android.product&#xD;&#xA;if exist &quot;$(ProjectDir)..\..\Binaries\NeoAxis.Internal\Platforms\Windows\CommandLineTools\CommandLineTools.exe&quot; &quot;$(ProjectDir)..\..\Binaries\NeoAxis.Internal\Platforms\Windows\CommandLineTools\CommandLineTools.exe&quot; -prepareProductAssets 1 -productFile &quot;%25Product%25&quot; -destinationFolder &quot;$(ProjectDir)Assets&quot; -platform Android" />
  </Target>
  <Target Name="FailIfOptimizeEnabled" BeforeTargets="BeforeBuild">
    <Error Condition="'$(Optimize)' == 'true'" Text="Optimize must be disabled. Current configuration has Optimize=$(Optimize)." />
  </Target>
</Project>