<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <UseUwp>true</UseUwp>
    <Platforms>x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>en-US</DefaultLanguage>

    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>False</PublishAot>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    
    <EnableMsixTooling>true</EnableMsixTooling>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>NeoAxis.Player</RootNamespace>
    <AssemblyName>NeoAxis.Player</AssemblyName>
    <PackageCertificateKeyFile>NeoAxis.Player.UWP_TemporaryKey.pfx</PackageCertificateKeyFile>
    <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
    <PackageCertificateThumbprint>2A2010862FA2191EF975658C1F5BB8F601888DB3</PackageCertificateThumbprint>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>C:\_TestUWP\</OutputPath>
  </PropertyGroup>  
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>UWP;DEPLOY;CLIENT;TRACE;DEBUG</DefineConstants>
    <NoWarn>2008</NoWarn>
    <DebugType>full</DebugType>
    <ErrorReport>prompt</ErrorReport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <DefineConstants>UWP;DEPLOY;CLIENT;RELEASE</DefineConstants>
    <Optimize>True</Optimize>
    <DebugOptimization>True</DebugOptimization>
    <DebugType>portable</DebugType>
    <NoWarn>2008</NoWarn>
    <DebugType>pdbonly</DebugType>
    <ErrorReport>prompt</ErrorReport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Implementation\EngineApp\UWP Specific\AppViewUWP.cs" />
    <Compile Include="Implementation\EngineApp\UWP Specific\FunctionalityUWP.cs" />
    <Compile Include="Implementation\EngineApp\UWP Specific\FunctionalityUWP.Cursor.cs" />
    <Compile Include="Implementation\EngineApp\UWP Specific\FunctionalityUWP.Input.cs" />
    <Compile Include="Implementation\EngineApp\UWP Specific\FunctionalityUWP.Utility.cs" />
    <Compile Include="Implementation\EngineApp\UWP Specific\FunctionalityUWP.Video.cs" />
    <Compile Include="Implementation\EngineApp\UWP Specific\UWPInputDeviceManager.cs" />
    <Compile Include="Implementation\FileSystem\DebugUtil.cs" />
    <Compile Include="Implementation\FileSystem\PlatformSpecificUtilityUWP.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Project\Assets\Base\Scripts\ClientUtility.cs" />
    <Compile Include="Project\Assets\Base\Scripts\RunServer.cs" />
    <Compile Include="Project\Assets\Base\Scripts\NetworkLogic.cs" />
    <Compile Include="Project\Assets\Base\Scripts\CloudServiceClient.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MultiplayerCreateWindow.cs" />
    <Compile Include="Project\Assets\Base\Scripts\SimulationAppClient.cs" />
    <Compile Include="Project\Assets\Base\Scripts\SimulationAppServer.cs" />
    <Compile Include="Project\Assets\Base\Scripts\SimulationApp.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MainMenuScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MenuWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\OptionsWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\ScenesWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\PlayScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\SplashScreen.cs" />
    <Compile Include="Project\Assets\Base\Scripts\ProjectAssembly.cs" />
    <Compile Include="Project\Assets\Base\UI\Styles\UIStyleEditor.cs" />
    <Compile Include="Project\Assets\Base\UI\Styles\UIStyleSimple.cs" />
    <Compile Include="Project\Assets\Base\UI\Windows\MessageBoxWindow.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\Scripts\ShooterCommon.cs" />
    <Compile Include="Project\Assets\Samples\Simple Game\SimpleGameGUI.cs" />
    <Compile Include="Project\Caches\CSharpScripts\CSharpScripts.cs" />
    <Compile Include="Project\Assets\Base\WindowApp\WindowAppMainForm.cs" />
    <Compile Include="Project\Assets\Samples\Spaceship Game\SpaceshipGameGUI.cs" />
    <Compile Include="Project\Assets\Samples\Platform Game\PlatformGameGUI.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\Scripts\ShooterNetworkLogic.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\UI\ShooterInGameContextScreen.cs" />
    <Compile Include="Project\Assets\Samples\Shooter\UI\ShooterSceneScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MultiplayerJoinWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\BasicSceneScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\EntranceScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\InGameContextScreen.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\AvatarWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MatchesWindow.cs" />
    <Compile Include="Project\Assets\Base\UI\Screens\MatchWindow.cs" />
  </ItemGroup>
  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest">
      <SubType>Designer</SubType>
    </AppxManifest>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
    <Content Include="..\..\Assets" />
    <Content Include="..\..\Caches" />
    <Content Include="..\..\Binaries\NeoAxis.Internal\Platforms\UWP\x64\libNeoAxisCoreNative.dll">
      <Link>NeoAxis.Internal\Platforms\UWP\x64\libNeoAxisCoreNative.dll</Link>
    </Content>
    <Content Include="..\..\Binaries\NeoAxis.Internal\NeoAxis.DefaultSettings.config">
      <Link>NeoAxis.Internal\NeoAxis.DefaultSettings.config</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Project\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="NeoAxis.Core">
      <HintPath>..\..\Binaries\NeoAxis.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <Target Name="RunCommandLineTools" BeforeTargets="BeforeBuild">
    <Exec Condition="Exists('$(ProjectDir)..\..\Project.csproj') and Exists('$(ProjectDir)..\..\Binaries\NeoAxis.Internal\Platforms\Windows\CommandLineTools\CommandLineTools.exe')" Command="&quot;$(ProjectDir)..\..\Binaries\NeoAxis.Internal\Platforms\Windows\CommandLineTools\CommandLineTools.exe&quot; -platformProjectPatchWithCopyFiles &quot;$(ProjectDir)NeoAxis.Player.UWP.csproj&quot; -baseProject &quot;$(ProjectDir)..\..\Project.csproj&quot;" />
  </Target>  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|arm64'">
    <Optimize>True</Optimize>
    <DebugOptimization>True</DebugOptimization>
    <DebugType>portable</DebugType>
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|arm64'">
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>