using System.ComponentModel;
using System.Drawing;

namespace System.Windows.Forms
{
	public class ToolStripDropDown : ToolStrip
	{
		public class ToolStripDropDownAccessibleObject : ToolStripAccessibleObject
		{
			public override string Name
			{
				get
				{
					throw null;
				}
				set
				{
					throw null;
				}
			}

			public override AccessibleRole Role
			{
				get
				{
					throw null;
				}
			}

			public ToolStripDropDownAccessibleObject(ToolStripDropDown owner)
				: base( owner )
			{
				throw null;
			}
		}

		public new bool AllowItemReorder
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public bool AllowTransparency
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public override AnchorStyles Anchor
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public override bool AutoSize
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public bool AutoClose
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new bool CanOverflow
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new ContextMenu ContextMenu
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new ContextMenuStrip ContextMenuStrip
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		protected override CreateParams CreateParams
		{
			get
			{
				throw null;
			}
		}

		protected override Padding DefaultPadding
		{
			get
			{
				throw null;
			}
		}

		protected override bool DefaultShowItemToolTips
		{
			get
			{
				throw null;
			}
		}

		protected override DockStyle DefaultDock
		{
			get
			{
				throw null;
			}
		}

		public override ToolStripDropDownDirection DefaultDropDownDirection
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public override DockStyle Dock
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public bool DropShadowEnabled
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public override Font Font
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new ToolStripGripDisplayStyle GripDisplayStyle
		{
			get
			{
				throw null;
			}
		}

		public new Rectangle GripRectangle
		{
			get
			{
				throw null;
			}
		}

		public new Padding GripMargin
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new ToolStripGripStyle GripStyle
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public bool IsAutoGenerated
		{
			get
			{
				throw null;
			}
		}

		public new Point Location
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public double Opacity
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new ToolStripOverflowButton OverflowButton
		{
			get
			{
				throw null;
			}
		}

		public ToolStripItem OwnerItem
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new Region Region
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public override RightToLeft RightToLeft
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new bool Stretch
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public override ToolStripTextDirection TextDirection
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		protected virtual bool TopMost
		{
			get
			{
				throw null;
			}
		}

		public bool TopLevel
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new int TabIndex
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new bool Visible
		{
			get
			{
				throw null;
			}
			set
			{
				throw null;
			}
		}

		public new event EventHandler BackgroundImageChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler BackgroundImageLayoutChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler BindingContextChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event UICuesEventHandler ChangeUICues
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler ContextMenuChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler ContextMenuStripChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler DockChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public event ToolStripDropDownClosedEventHandler Closed
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public event ToolStripDropDownClosingEventHandler Closing
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler Enter
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler FontChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler ForeColorChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event GiveFeedbackEventHandler GiveFeedback
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event HelpEventHandler HelpRequested
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler ImeModeChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event KeyEventHandler KeyDown
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event KeyPressEventHandler KeyPress
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event KeyEventHandler KeyUp
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler Leave
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public event CancelEventHandler Opening
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public event EventHandler Opened
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler RegionChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event ScrollEventHandler Scroll
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler StyleChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler TabStopChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler TextChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler TabIndexChanged
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event EventHandler Validated
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public new event CancelEventHandler Validating
		{
			add
			{
				throw null;
			}
			remove
			{
				throw null;
			}
		}

		public ToolStripDropDown()
		{
			throw null;
		}

		protected override void Dispose(bool disposing)
		{
			throw null;
		}

		protected override AccessibleObject CreateAccessibilityInstance()
		{
			throw null;
		}

		protected override LayoutSettings CreateLayoutSettings(ToolStripLayoutStyle style)
		{
			throw null;
		}

		protected override void CreateHandle()
		{
			throw null;
		}

		public void Close()
		{
			throw null;
		}

		public void Close(ToolStripDropDownCloseReason reason)
		{
			throw null;
		}

		protected virtual void OnClosed(ToolStripDropDownClosedEventArgs e)
		{
			throw null;
		}

		protected virtual void OnClosing(ToolStripDropDownClosingEventArgs e)
		{
			throw null;
		}

		protected override void OnHandleCreated(EventArgs e)
		{
			throw null;
		}

		protected override void OnItemClicked(ToolStripItemClickedEventArgs e)
		{
			throw null;
		}

		protected override void OnLayout(LayoutEventArgs e)
		{
			throw null;
		}

		protected virtual void OnOpening(CancelEventArgs e)
		{
			throw null;
		}

		protected virtual void OnOpened(EventArgs e)
		{
			throw null;
		}

		protected override void OnVisibleChanged(EventArgs e)
		{
			throw null;
		}

		protected override void OnParentChanged(EventArgs e)
		{
			throw null;
		}

		protected override void OnMouseUp(MouseEventArgs mea)
		{
			throw null;
		}

		protected override bool ProcessDialogKey(Keys keyData)
		{
			throw null;
		}

		protected override bool ProcessDialogChar(char charCode)
		{
			throw null;
		}

		protected override void ScaleCore(float dx, float dy)
		{
			throw null;
		}

		protected override void ScaleControl(SizeF factor, BoundsSpecified specified)
		{
			throw null;
		}

		protected override void SetBoundsCore(int x, int y, int width, int height, BoundsSpecified specified)
		{
			throw null;
		}

		protected override void SetVisibleCore(bool visible)
		{
			throw null;
		}

		public new void Show()
		{
			throw null;
		}

		public void Show(Control control, Point position)
		{
			throw null;
		}

		public void Show(Control control, Point position, ToolStripDropDownDirection direction)
		{
			throw null;
		}

		public void Show(Control control, int x, int y)
		{
			throw null;
		}

		public void Show(Point screenLocation)
		{
			throw null;
		}

		public void Show(Point position, ToolStripDropDownDirection direction)
		{
			throw null;
		}

		public void Show(int x, int y)
		{
			throw null;
		}

		protected override void WndProc(ref Message m)
		{
			throw null;
		}
	}
}
