namespace System.Drawing.Imaging
{
	public enum EncoderValue
	{
		ColorTypeCMYK,
		ColorTypeYCCK,
		CompressionLZW,
		CompressionCCITT3,
		CompressionCCITT4,
		CompressionRle,
		CompressionNone,
		ScanMethodInterlaced,
		ScanMethodNonInterlaced,
		VersionGif87,
		VersionGif89,
		RenderProgressive,
		RenderNonProgressive,
		TransformRotate90,
		TransformRotate180,
		TransformRotate270,
		TransformFlipHorizontal,
		TransformFlipVertical,
		MultiFrame,
		LastFrame,
		Flush,
		FrameDimensionTime,
		FrameDimensionResolution,
		FrameDimensionPage
	}
}
