<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  	<UseWindowsForms>true</UseWindowsForms>
  	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\Binaries\</OutputPath>
    <Optimize>True</Optimize>
    <DebugOptimization>True</DebugOptimization>
    <DebugType>portable</DebugType>
    <NoWarn>1701;1702;CA1416;MSB3277;MSB3277</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\Binaries\</OutputPath>
    <NoWarn>1701;1702;CA1416;MSB3277;MSB3277</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="NeoAxis.Core">
      <HintPath>..\..\Binaries\NeoAxis.Core.dll</HintPath>
    </Reference>
    <Reference Include="NeoAxis.Core.Editor">
      <HintPath>..\..\Binaries\NeoAxis.Core.Editor.dll</HintPath>
    </Reference>
    <Reference Include="NeoAxis.Widget">
      <HintPath>..\..\Binaries\NeoAxis.Widget.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>