//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxAnimCurveKey : FbxAnimCurveKeyBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxAnimCurveKey(global::System.IntPtr cPtr, bool cMemoryOwn) : base(FbxWrapperNativePINVOKE.FbxAnimCurveKey_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxAnimCurveKey obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxAnimCurveKey() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FbxWrapperNativePINVOKE.delete_FbxAnimCurveKey(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public FbxAnimCurveKey() : this(FbxWrapperNativePINVOKE.new_FbxAnimCurveKey__SWIG_0(), true) {
  }

  public FbxAnimCurveKey(FbxTime pTime) : this(FbxWrapperNativePINVOKE.new_FbxAnimCurveKey__SWIG_1(FbxTime.getCPtr(pTime)), true) {
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxAnimCurveKey(FbxTime pTime, float pVal) : this(FbxWrapperNativePINVOKE.new_FbxAnimCurveKey__SWIG_2(FbxTime.getCPtr(pTime), pVal), true) {
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxAnimCurveKey(FbxAnimCurveKey pFKey) : this(FbxWrapperNativePINVOKE.new_FbxAnimCurveKey__SWIG_3(FbxAnimCurveKey.getCPtr(pFKey)), true) {
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxAnimCurveKey assign(FbxAnimCurveKey pFKey) {
    FbxAnimCurveKey ret = new FbxAnimCurveKey(FbxWrapperNativePINVOKE.FbxAnimCurveKey_assign(swigCPtr, FbxAnimCurveKey.getCPtr(pFKey)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override FbxTime GetTime() {
    FbxTime ret = new FbxTime(FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetTime(swigCPtr), true);
    return ret;
  }

  public override void SetTime(FbxTime pTime) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTime(swigCPtr, FbxTime.getCPtr(pTime));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set(FbxTime pTime, float pValue) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_Set(swigCPtr, FbxTime.getCPtr(pTime), pValue);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTCB(FbxTime pTime, float pValue, float pData0, float pData1, float pData2) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTCB__SWIG_0(swigCPtr, FbxTime.getCPtr(pTime), pValue, pData0, pData1, pData2);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTCB(FbxTime pTime, float pValue, float pData0, float pData1) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTCB__SWIG_1(swigCPtr, FbxTime.getCPtr(pTime), pValue, pData0, pData1);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTCB(FbxTime pTime, float pValue, float pData0) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTCB__SWIG_2(swigCPtr, FbxTime.getCPtr(pTime), pValue, pData0);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTCB(FbxTime pTime, float pValue) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTCB__SWIG_3(swigCPtr, FbxTime.getCPtr(pTime), pValue);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public float GetValue() {
    float ret = FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetValue(swigCPtr);
    return ret;
  }

  public void SetValue(float pValue) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetValue(swigCPtr, pValue);
  }

  public FbxAnimCurveDef.EInterpolationType GetInterpolation() {
    FbxAnimCurveDef.EInterpolationType ret = (FbxAnimCurveDef.EInterpolationType)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetInterpolation(swigCPtr);
    return ret;
  }

  public void SetInterpolation(FbxAnimCurveDef.EInterpolationType pInterpolation) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetInterpolation(swigCPtr, (int)pInterpolation);
  }

  public FbxAnimCurveDef.ETangentMode GetTangentMode(bool pIncludeOverrides) {
    FbxAnimCurveDef.ETangentMode ret = (FbxAnimCurveDef.ETangentMode)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetTangentMode__SWIG_0(swigCPtr, pIncludeOverrides);
    return ret;
  }

  public FbxAnimCurveDef.ETangentMode GetTangentMode() {
    FbxAnimCurveDef.ETangentMode ret = (FbxAnimCurveDef.ETangentMode)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetTangentMode__SWIG_1(swigCPtr);
    return ret;
  }

  public void SetTangentMode(FbxAnimCurveDef.ETangentMode pTangentMode) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentMode(swigCPtr, (int)pTangentMode);
  }

  public FbxAnimCurveDef.EWeightedMode GetTangentWeightMode() {
    FbxAnimCurveDef.EWeightedMode ret = (FbxAnimCurveDef.EWeightedMode)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetTangentWeightMode(swigCPtr);
    return ret;
  }

  public void SetTangentWeightMode(FbxAnimCurveDef.EWeightedMode pTangentWeightMode, FbxAnimCurveDef.EWeightedMode pMask) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentWeightMode__SWIG_0(swigCPtr, (int)pTangentWeightMode, (int)pMask);
  }

  public void SetTangentWeightMode(FbxAnimCurveDef.EWeightedMode pTangentWeightMode) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentWeightMode__SWIG_1(swigCPtr, (int)pTangentWeightMode);
  }

  public void SetTangentWeightAndAdjustTangent(FbxAnimCurveDef.EDataIndex pIndex, double pWeight) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentWeightAndAdjustTangent(swigCPtr, (int)pIndex, pWeight);
  }

  public FbxAnimCurveDef.EVelocityMode GetTangentVelocityMode() {
    FbxAnimCurveDef.EVelocityMode ret = (FbxAnimCurveDef.EVelocityMode)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetTangentVelocityMode(swigCPtr);
    return ret;
  }

  public void SetTangentVelocityMode(FbxAnimCurveDef.EVelocityMode pTangentVelocityMode, FbxAnimCurveDef.EVelocityMode pMask) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentVelocityMode__SWIG_0(swigCPtr, (int)pTangentVelocityMode, (int)pMask);
  }

  public void SetTangentVelocityMode(FbxAnimCurveDef.EVelocityMode pTangentVelocityMode) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentVelocityMode__SWIG_1(swigCPtr, (int)pTangentVelocityMode);
  }

  public FbxAnimCurveDef.EConstantMode GetConstantMode() {
    FbxAnimCurveDef.EConstantMode ret = (FbxAnimCurveDef.EConstantMode)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetConstantMode(swigCPtr);
    return ret;
  }

  public void SetConstantMode(FbxAnimCurveDef.EConstantMode pMode) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetConstantMode(swigCPtr, (int)pMode);
  }

  public float GetDataFloat(FbxAnimCurveDef.EDataIndex pIndex) {
    float ret = FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetDataFloat(swigCPtr, (int)pIndex);
    return ret;
  }

  public void SetDataFloat(FbxAnimCurveDef.EDataIndex pIndex, float pValue) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetDataFloat(swigCPtr, (int)pIndex, pValue);
  }

  public void SetTangentVisibility(FbxAnimCurveDef.ETangentVisibility pVisibility) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetTangentVisibility(swigCPtr, (int)pVisibility);
  }

  public FbxAnimCurveDef.ETangentVisibility GetTangentVisibility() {
    FbxAnimCurveDef.ETangentVisibility ret = (FbxAnimCurveDef.ETangentVisibility)FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetTangentVisibility(swigCPtr);
    return ret;
  }

  public void SetBreak(bool pVal) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetBreak(swigCPtr, pVal);
  }

  public bool GetBreak() {
    bool ret = FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetBreak(swigCPtr);
    return ret;
  }

  public FbxAnimCurveKey_Impl GetImpl() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxAnimCurveKey_GetImpl(swigCPtr);
    FbxAnimCurveKey_Impl ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxAnimCurveKey_Impl(cPtr, false);
    return ret;
  }

  public static void SetAllocatorFct(SWIGTYPE_p_f___p_FbxAnimCurveKey_Impl pAllocatorFct) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetAllocatorFct(SWIGTYPE_p_f___p_FbxAnimCurveKey_Impl.getCPtr(pAllocatorFct));
  }

  public static void SetCopyAllocatorFct(SWIGTYPE_p_f_p_FbxAnimCurveKey_Impl__p_FbxAnimCurveKey_Impl pCopyAllocatorFct) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetCopyAllocatorFct(SWIGTYPE_p_f_p_FbxAnimCurveKey_Impl__p_FbxAnimCurveKey_Impl.getCPtr(pCopyAllocatorFct));
  }

  public static void SetDeallocatorFct(SWIGTYPE_p_f_p_FbxAnimCurveKey_Impl__void pDeallocatorFct) {
    FbxWrapperNativePINVOKE.FbxAnimCurveKey_SetDeallocatorFct(SWIGTYPE_p_f_p_FbxAnimCurveKey_Impl__void.getCPtr(pDeallocatorFct));
  }

}

}
