//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxContainerTemplate : FbxObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxContainerTemplate(global::System.IntPtr cPtr, bool cMemoryOwn) : base(FbxWrapperNativePINVOKE.FbxContainerTemplate_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxContainerTemplate obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      FbxWrapperNativePINVOKE.FbxContainerTemplate_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(FbxWrapperNativePINVOKE.FbxContainerTemplate_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxContainerTemplate Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxContainerTemplate ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxContainerTemplate(cPtr, false);
    return ret;
  }

  public new static FbxContainerTemplate Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxContainerTemplate ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxContainerTemplate(cPtr, false);
    return ret;
  }

  public void ParseTemplateFile(string pTemplateFilePath, SWIGTYPE_p_FbxArrayT_FbxString_p_t pExtendTemplateNames) {
    FbxWrapperNativePINVOKE.FbxContainerTemplate_ParseTemplateFile(swigCPtr, pTemplateFilePath, SWIGTYPE_p_FbxArrayT_FbxString_p_t.getCPtr(pExtendTemplateNames));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddExtendTemplatePath(string pExtendTemplatePath) {
    FbxWrapperNativePINVOKE.FbxContainerTemplate_AddExtendTemplatePath(swigCPtr, pExtendTemplatePath);
  }

  public string GetExtendTemplatePathAt(uint pIndex) {
    string ret = FbxWrapperNativePINVOKE.FbxContainerTemplate_GetExtendTemplatePathAt(swigCPtr, pIndex);
    return ret;
  }

  public uint GetExtendTemplateCount() {
    uint ret = FbxWrapperNativePINVOKE.FbxContainerTemplate_GetExtendTemplateCount(swigCPtr);
    return ret;
  }

  public void ClearExtendTemplatePath() {
    FbxWrapperNativePINVOKE.FbxContainerTemplate_ClearExtendTemplatePath(swigCPtr);
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t ContainerTemplateName {
    set {
      FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplateName_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplateName_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t ContainerTemplatePath {
    set {
      FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplatePath_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplatePath_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t ContainerTemplatePackageName {
    set {
      FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplatePackageName_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplatePackageName_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t ContainerTemplateVersion {
    set {
      FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplateVersion_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxContainerTemplate_ContainerTemplateVersion_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

}

}
