//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxDistance : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxDistance(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxDistance obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxDistance() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FbxWrapperNativePINVOKE.delete_FbxDistance(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxDistance() : this(FbxWrapperNativePINVOKE.new_FbxDistance__SWIG_0(), true) {
  }

  public FbxDistance(float pValue, FbxSystemUnit pUnit) : this(FbxWrapperNativePINVOKE.new_FbxDistance__SWIG_1(pValue, FbxSystemUnit.getCPtr(pUnit)), true) {
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxDistance(float pValue, string pUnit) : this(FbxWrapperNativePINVOKE.new_FbxDistance__SWIG_2(pValue, pUnit), true) {
  }

  public FbxDistance assign(FbxDistance pValue) {
    FbxDistance ret = new FbxDistance(FbxWrapperNativePINVOKE.FbxDistance_assign(swigCPtr, FbxDistance.getCPtr(pValue)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool eq(FbxDistance pRHS) {
    bool ret = FbxWrapperNativePINVOKE.FbxDistance_eq(swigCPtr, FbxDistance.getCPtr(pRHS));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ne(FbxDistance pRHS) {
    bool ret = FbxWrapperNativePINVOKE.FbxDistance_ne(swigCPtr, FbxDistance.getCPtr(pRHS));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxString unitName() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxDistance_unitName(swigCPtr), true);
    return ret;
  }

  public FbxSystemUnit unit() {
    FbxSystemUnit ret = new FbxSystemUnit(FbxWrapperNativePINVOKE.FbxDistance_unit(swigCPtr), true);
    return ret;
  }

  public float value() {
    float ret = FbxWrapperNativePINVOKE.FbxDistance_value(swigCPtr);
    return ret;
  }

  public float internalValue() {
    float ret = FbxWrapperNativePINVOKE.FbxDistance_internalValue(swigCPtr);
    return ret;
  }

  public float valueAs(FbxSystemUnit pUnit) {
    float ret = FbxWrapperNativePINVOKE.FbxDistance_valueAs(swigCPtr, FbxSystemUnit.getCPtr(pUnit));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
