//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxFile : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxFile(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxFile obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxFile() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FbxWrapperNativePINVOKE.delete_FbxFile(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxFile() : this(FbxWrapperNativePINVOKE.new_FbxFile(), true) {
  }

  public virtual bool Open(string pFileName_UTF8, FbxFile.EMode pMode, bool pBinary) {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_Open__SWIG_0(swigCPtr, pFileName_UTF8, (int)pMode, pBinary);
    return ret;
  }

  public virtual bool Open(string pFileName_UTF8, FbxFile.EMode pMode) {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_Open__SWIG_1(swigCPtr, pFileName_UTF8, (int)pMode);
    return ret;
  }

  public virtual bool Open(string pFileName_UTF8) {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_Open__SWIG_2(swigCPtr, pFileName_UTF8);
    return ret;
  }

  public virtual bool Open(FbxStream pStream, SWIGTYPE_p_void pStreamData, string pMode) {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_Open__SWIG_3(swigCPtr, FbxStream.getCPtr(pStream), SWIGTYPE_p_void.getCPtr(pStreamData), pMode);
    return ret;
  }

  public virtual bool Close() {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_Close(swigCPtr);
    return ret;
  }

  public virtual void Seek(SWIGTYPE_p_signed___int64 pOffset, FbxFile.ESeekPos pSeekPos) {
    FbxWrapperNativePINVOKE.FbxFile_Seek__SWIG_0(swigCPtr, SWIGTYPE_p_signed___int64.getCPtr(pOffset), (int)pSeekPos);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void Seek(SWIGTYPE_p_signed___int64 pOffset) {
    FbxWrapperNativePINVOKE.FbxFile_Seek__SWIG_1(swigCPtr, SWIGTYPE_p_signed___int64.getCPtr(pOffset));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_signed___int64 Tell() {
    SWIGTYPE_p_signed___int64 ret = new SWIGTYPE_p_signed___int64(FbxWrapperNativePINVOKE.FbxFile_Tell(swigCPtr), true);
    return ret;
  }

  public virtual uint Read(SWIGTYPE_p_void pDstBuf, uint pSize) {
    uint ret = FbxWrapperNativePINVOKE.FbxFile_Read(swigCPtr, SWIGTYPE_p_void.getCPtr(pDstBuf), pSize);
    return ret;
  }

  public virtual string ReadString(string pDstBuf, uint pDstSize, bool pStopAtFirstWhiteSpace) {
    string ret = FbxWrapperNativePINVOKE.FbxFile_ReadString__SWIG_0(swigCPtr, pDstBuf, pDstSize, pStopAtFirstWhiteSpace);
    return ret;
  }

  public virtual string ReadString(string pDstBuf, uint pDstSize) {
    string ret = FbxWrapperNativePINVOKE.FbxFile_ReadString__SWIG_1(swigCPtr, pDstBuf, pDstSize);
    return ret;
  }

  public virtual uint Write(SWIGTYPE_p_void pSrcBuf, uint pSize) {
    uint ret = FbxWrapperNativePINVOKE.FbxFile_Write(swigCPtr, SWIGTYPE_p_void.getCPtr(pSrcBuf), pSize);
    return ret;
  }

  public virtual bool WriteFormat(string pFormat) {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_WriteFormat(swigCPtr, pFormat);
    return ret;
  }

  public virtual bool Truncate(SWIGTYPE_p_signed___int64 pSize) {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_Truncate(swigCPtr, SWIGTYPE_p_signed___int64.getCPtr(pSize));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool EndOfFile() {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_EndOfFile(swigCPtr);
    return ret;
  }

  public virtual SWIGTYPE_p_signed___int64 GetSize() {
    SWIGTYPE_p_signed___int64 ret = new SWIGTYPE_p_signed___int64(FbxWrapperNativePINVOKE.FbxFile_GetSize(swigCPtr), true);
    return ret;
  }

  public virtual void GetMemoryFileInfo(SWIGTYPE_p_p_void pMemPtr, uint pSize) {
    FbxWrapperNativePINVOKE.FbxFile_GetMemoryFileInfo(swigCPtr, SWIGTYPE_p_p_void.getCPtr(pMemPtr), pSize);
  }

  public bool IsOpen() {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_IsOpen(swigCPtr);
    return ret;
  }

  public bool IsStream() {
    bool ret = FbxWrapperNativePINVOKE.FbxFile_IsStream(swigCPtr);
    return ret;
  }

  public string GetFilePathName() {
    string ret = FbxWrapperNativePINVOKE.FbxFile_GetFilePathName(swigCPtr);
    return ret;
  }

  public FbxFile.EMode GetFileMode() {
    FbxFile.EMode ret = (FbxFile.EMode)FbxWrapperNativePINVOKE.FbxFile_GetFileMode(swigCPtr);
    return ret;
  }

  public int GetLastError() {
    int ret = FbxWrapperNativePINVOKE.FbxFile_GetLastError(swigCPtr);
    return ret;
  }

  public void ClearError() {
    FbxWrapperNativePINVOKE.FbxFile_ClearError(swigCPtr);
  }

  public enum EMode {
    eNone,
    eReadOnly,
    eReadWrite,
    eCreateWriteOnly,
    eCreateReadWrite,
    eCreateAppend
  }

  public enum ESeekPos {
    eBegin,
    eCurrent,
    eEnd
  }

}

}
