//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxGeometryWeightedMap : FbxObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxGeometryWeightedMap(global::System.IntPtr cPtr, bool cMemoryOwn) : base(FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxGeometryWeightedMap obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxGeometryWeightedMap Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxGeometryWeightedMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGeometryWeightedMap(cPtr, false);
    return ret;
  }

  public new static FbxGeometryWeightedMap Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxGeometryWeightedMap ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGeometryWeightedMap(cPtr, false);
    return ret;
  }

  public void SetValues(FbxWeightedMapping pWeightedMappingTable) {
    FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_SetValues(swigCPtr, FbxWeightedMapping.getCPtr(pWeightedMappingTable));
  }

  public FbxWeightedMapping GetValues() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_GetValues(swigCPtr);
    FbxWeightedMapping ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxWeightedMapping(cPtr, false);
    return ret;
  }

  public FbxGeometry GetSourceGeometry() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_GetSourceGeometry(swigCPtr);
    FbxGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGeometry(cPtr, false);
    return ret;
  }

  public FbxGeometry GetDestinationGeometry() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_GetDestinationGeometry(swigCPtr);
    FbxGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGeometry(cPtr, false);
    return ret;
  }

  public override FbxObject Copy(FbxObject pObject) {
    FbxObject ret = new FbxObject(FbxWrapperNativePINVOKE.FbxGeometryWeightedMap_Copy(swigCPtr, FbxObject.getCPtr(pObject)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
