//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxIOFileHeaderInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxIOFileHeaderInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxIOFileHeaderInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxIOFileHeaderInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FbxWrapperNativePINVOKE.delete_FbxIOFileHeaderInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxIOFileHeaderInfo() : this(FbxWrapperNativePINVOKE.new_FbxIOFileHeaderInfo(), true) {
  }

  public virtual void Reset() {
    FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_Reset(swigCPtr);
  }

  public virtual bool ReadExtendedHeaderInformation(FbxIO arg0) {
    bool ret = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_ReadExtendedHeaderInformation(swigCPtr, FbxIO.getCPtr(arg0));
    return ret;
  }

  public FbxIODefaultRenderResolution mDefaultRenderResolution {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mDefaultRenderResolution_set(swigCPtr, FbxIODefaultRenderResolution.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mDefaultRenderResolution_get(swigCPtr);
      FbxIODefaultRenderResolution ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxIODefaultRenderResolution(cPtr, false);
      return ret;
    } 
  }

  public int mFileVersion {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mFileVersion_set(swigCPtr, value);
    } 
    get {
      int ret = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mFileVersion_get(swigCPtr);
      return ret;
    } 
  }

  public bool mCreationTimeStampPresent {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mCreationTimeStampPresent_set(swigCPtr, value);
    } 
    get {
      bool ret = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mCreationTimeStampPresent_get(swigCPtr);
      return ret;
    } 
  }

  public FbxLocalTime mCreationTimeStamp {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mCreationTimeStamp_set(swigCPtr, FbxLocalTime.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mCreationTimeStamp_get(swigCPtr);
      FbxLocalTime ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLocalTime(cPtr, false);
      return ret;
    } 
  }

  public FbxString mCreator {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mCreator_set(swigCPtr, FbxString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mCreator_get(swigCPtr);
      FbxString ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxString(cPtr, false);
      return ret;
    } 
  }

  public bool mIOPlugin {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mIOPlugin_set(swigCPtr, value);
    } 
    get {
      bool ret = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mIOPlugin_get(swigCPtr);
      return ret;
    } 
  }

  public bool mPLE {
    set {
      FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mPLE_set(swigCPtr, value);
    } 
    get {
      bool ret = FbxWrapperNativePINVOKE.FbxIOFileHeaderInfo_mPLE_get(swigCPtr);
      return ret;
    } 
  }

}

}
