//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxLayerElementHole : FbxLayerElementTemplateFbxBool {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxLayerElementHole(global::System.IntPtr cPtr, bool cMemoryOwn) : base(FbxWrapperNativePINVOKE.FbxLayerElementHole_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxLayerElementHole obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxLayerElementHole() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FbxWrapperNativePINVOKE.delete_FbxLayerElementHole(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxLayerElementHole Create(FbxLayerContainer pOwner, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxLayerElementHole_Create(FbxLayerContainer.getCPtr(pOwner), pName);
    FbxLayerElementHole ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLayerElementHole(cPtr, false);
    return ret;
  }

  public new void SetReferenceMode(FbxLayerElement.EReferenceMode pMode) {
    FbxWrapperNativePINVOKE.FbxLayerElementHole_SetReferenceMode(swigCPtr, (int)pMode);
  }

}

}
