//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxLayerElementTemplateFbxSurfaceMaterialPtr : FbxLayerElement {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxLayerElementTemplateFbxSurfaceMaterialPtr(global::System.IntPtr cPtr, bool cMemoryOwn) : base(FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxLayerElementTemplateFbxSurfaceMaterialPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr GetDirectArray() {
    FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr ret = new FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr(FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_GetDirectArray__SWIG_0(swigCPtr), false);
    return ret;
  }

  public FbxLayerElementArrayTemplateFbxInt GetIndexArray() {
    FbxLayerElementArrayTemplateFbxInt ret = new FbxLayerElementArrayTemplateFbxInt(FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_GetIndexArray__SWIG_0(swigCPtr), false);
    return ret;
  }

  public override bool Clear() {
    bool ret = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_Clear(swigCPtr);
    return ret;
  }

  public bool eq(FbxLayerElementTemplateFbxSurfaceMaterialPtr pOther) {
    bool ret = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_eq(swigCPtr, FbxLayerElementTemplateFbxSurfaceMaterialPtr.getCPtr(pOther));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxLayerElementTemplateFbxSurfaceMaterialPtr assign(FbxLayerElementTemplateFbxSurfaceMaterialPtr pOther) {
    FbxLayerElementTemplateFbxSurfaceMaterialPtr ret = new FbxLayerElementTemplateFbxSurfaceMaterialPtr(FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_assign(swigCPtr, FbxLayerElementTemplateFbxSurfaceMaterialPtr.getCPtr(pOther)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int RemapIndexTo(FbxLayerElement.EMappingMode pNewMapping) {
    int ret = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_RemapIndexTo(swigCPtr, (int)pNewMapping);
    return ret;
  }

  public override int MemorySize() {
    int ret = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_MemorySize(swigCPtr);
    return ret;
  }

  public override bool ContentWriteTo(FbxStream pStream) {
    bool ret = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_ContentWriteTo(swigCPtr, FbxStream.getCPtr(pStream));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool ContentReadFrom(FbxStream pStream) {
    bool ret = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_ContentReadFrom(swigCPtr, FbxStream.getCPtr(pStream));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr mDirectArray {
    set {
      FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_mDirectArray_set(swigCPtr, FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_mDirectArray_get(swigCPtr);
      FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLayerElementArrayTemplateFbxSurfaceMaterialPtr(cPtr, false);
      return ret;
    } 
  }

  public FbxLayerElementArrayTemplateFbxInt mIndexArray {
    set {
      FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_mIndexArray_set(swigCPtr, FbxLayerElementArrayTemplateFbxInt.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxLayerElementTemplateFbxSurfaceMaterialPtr_mIndexArray_get(swigCPtr);
      FbxLayerElementArrayTemplateFbxInt ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLayerElementArrayTemplateFbxInt(cPtr, false);
      return ret;
    } 
  }

}

}
