//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxObject : FbxEmitter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxObject(global::System.IntPtr cPtr, bool cMemoryOwn) : base(FbxWrapperNativePINVOKE.FbxObject_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      FbxWrapperNativePINVOKE.FbxObject_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public virtual FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(FbxWrapperNativePINVOKE.FbxObject_GetClassId(swigCPtr), true);
    return ret;
  }

  public static FbxObject Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public static FbxObject Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxManager GetFbxManager() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetFbxManager(swigCPtr);
    FbxManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxManager(cPtr, false);
    return ret;
  }

  public FbxDocument GetDocument() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetDocument(swigCPtr);
    FbxDocument ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxDocument(cPtr, false);
    return ret;
  }

  public FbxDocument GetRootDocument() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetRootDocument(swigCPtr);
    FbxDocument ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxDocument(cPtr, false);
    return ret;
  }

  public FbxScene GetScene() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetScene(swigCPtr);
    FbxScene ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxScene(cPtr, false);
    return ret;
  }

  public void Destroy(bool pRecursive) {
    FbxWrapperNativePINVOKE.FbxObject_Destroy__SWIG_0(swigCPtr, pRecursive);
  }

  public void Destroy() {
    FbxWrapperNativePINVOKE.FbxObject_Destroy__SWIG_1(swigCPtr);
  }

  public void ResetProperties() {
    FbxWrapperNativePINVOKE.FbxObject_ResetProperties(swigCPtr);
  }

  public void SetObjectFlags(FbxObject.EObjectFlag pFlags, bool pValue) {
    FbxWrapperNativePINVOKE.FbxObject_SetObjectFlags(swigCPtr, (int)pFlags, pValue);
  }

  public bool GetObjectFlags(FbxObject.EObjectFlag pFlags) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_GetObjectFlags(swigCPtr, (int)pFlags);
    return ret;
  }

  public void SetAllObjectFlags(uint pFlags) {
    FbxWrapperNativePINVOKE.FbxObject_SetAllObjectFlags(swigCPtr, pFlags);
  }

  public uint GetAllObjectFlags() {
    uint ret = FbxWrapperNativePINVOKE.FbxObject_GetAllObjectFlags(swigCPtr);
    return ret;
  }

  public virtual FbxObject Copy(FbxObject pObject) {
    FbxObject ret = new FbxObject(FbxWrapperNativePINVOKE.FbxObject_Copy(swigCPtr, FbxObject.getCPtr(pObject)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual FbxObject Clone(FbxObject.ECloneType pCloneType, FbxObject pContainer, SWIGTYPE_p_void pSet) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_Clone__SWIG_0(swigCPtr, (int)pCloneType, FbxObject.getCPtr(pContainer), SWIGTYPE_p_void.getCPtr(pSet));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public virtual FbxObject Clone(FbxObject.ECloneType pCloneType, FbxObject pContainer) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_Clone__SWIG_1(swigCPtr, (int)pCloneType, FbxObject.getCPtr(pContainer));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public virtual FbxObject Clone(FbxObject.ECloneType pCloneType) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_Clone__SWIG_2(swigCPtr, (int)pCloneType);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public virtual FbxObject Clone() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_Clone__SWIG_3(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public bool IsAReferenceTo() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsAReferenceTo(swigCPtr);
    return ret;
  }

  public FbxObject GetReferenceTo() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetReferenceTo(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public bool IsReferencedBy() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsReferencedBy(swigCPtr);
    return ret;
  }

  public int GetReferencedByCount() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetReferencedByCount(swigCPtr);
    return ret;
  }

  public FbxObject GetReferencedBy(int pIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetReferencedBy(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public void SetName(string pName) {
    FbxWrapperNativePINVOKE.FbxObject_SetName(swigCPtr, pName);
  }

  public string GetName() {
    string ret = FbxWrapperNativePINVOKE.FbxObject_GetName(swigCPtr);
    return ret;
  }

  public FbxString GetNameWithoutNameSpacePrefix() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_GetNameWithoutNameSpacePrefix(swigCPtr), true);
    return ret;
  }

  public FbxString GetNameWithNameSpacePrefix() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_GetNameWithNameSpacePrefix(swigCPtr), true);
    return ret;
  }

  public void SetInitialName(string pName) {
    FbxWrapperNativePINVOKE.FbxObject_SetInitialName(swigCPtr, pName);
  }

  public string GetInitialName() {
    string ret = FbxWrapperNativePINVOKE.FbxObject_GetInitialName(swigCPtr);
    return ret;
  }

  public FbxString GetNameSpaceOnly() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_GetNameSpaceOnly(swigCPtr), true);
    return ret;
  }

  public void SetNameSpace(FbxString pNameSpace) {
    FbxWrapperNativePINVOKE.FbxObject_SetNameSpace(swigCPtr, FbxString.getCPtr(pNameSpace));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_FbxArrayT_FbxString_p_t GetNameSpaceArray(char identifier) {
    SWIGTYPE_p_FbxArrayT_FbxString_p_t ret = new SWIGTYPE_p_FbxArrayT_FbxString_p_t(FbxWrapperNativePINVOKE.FbxObject_GetNameSpaceArray(swigCPtr, identifier), true);
    return ret;
  }

  public FbxString GetNameOnly() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_GetNameOnly(swigCPtr), true);
    return ret;
  }

  public FbxString GetNameSpacePrefix() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_GetNameSpacePrefix(swigCPtr), true);
    return ret;
  }

  public static FbxString RemovePrefix(string pName) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_RemovePrefix(pName), true);
    return ret;
  }

  public static FbxString StripPrefix(FbxString lName) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_StripPrefix__SWIG_0(FbxString.getCPtr(lName)), true);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static FbxString StripPrefix(string pName) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_StripPrefix__SWIG_1(pName), true);
    return ret;
  }

  public ulong GetUniqueID() {
    ulong ret = FbxWrapperNativePINVOKE.FbxObject_GetUniqueID(swigCPtr);
    return ret;
  }

  public virtual bool GetSelected() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_GetSelected(swigCPtr);
    return ret;
  }

  public virtual void SetSelected(bool pSelected) {
    FbxWrapperNativePINVOKE.FbxObject_SetSelected(swigCPtr, pSelected);
  }

  public void SetUserDataPtr(ulong pUserID, SWIGTYPE_p_void pUserData) {
    FbxWrapperNativePINVOKE.FbxObject_SetUserDataPtr__SWIG_0(swigCPtr, pUserID, SWIGTYPE_p_void.getCPtr(pUserData));
  }

  public SWIGTYPE_p_void GetUserDataPtr(ulong pUserID) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetUserDataPtr__SWIG_0(swigCPtr, pUserID);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public void SetUserDataPtr(SWIGTYPE_p_void pUserData) {
    FbxWrapperNativePINVOKE.FbxObject_SetUserDataPtr__SWIG_1(swigCPtr, SWIGTYPE_p_void.getCPtr(pUserData));
  }

  public SWIGTYPE_p_void GetUserDataPtr() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetUserDataPtr__SWIG_1(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public bool ConnectSrcObject(FbxObject pObject, FbxConnection.EType pType) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ConnectSrcObject__SWIG_0(swigCPtr, FbxObject.getCPtr(pObject), (int)pType);
    return ret;
  }

  public bool ConnectSrcObject(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ConnectSrcObject__SWIG_1(swigCPtr, FbxObject.getCPtr(pObject));
    return ret;
  }

  public bool IsConnectedSrcObject(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsConnectedSrcObject(swigCPtr, FbxObject.getCPtr(pObject));
    return ret;
  }

  public bool DisconnectSrcObject(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectSrcObject(swigCPtr, FbxObject.getCPtr(pObject));
    return ret;
  }

  public bool DisconnectAllSrcObject() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectAllSrcObject__SWIG_0(swigCPtr);
    return ret;
  }

  public bool DisconnectAllSrcObject(FbxCriteria pCriteria) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectAllSrcObject__SWIG_1(swigCPtr, FbxCriteria.getCPtr(pCriteria));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetSrcObjectCount() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetSrcObjectCount__SWIG_0(swigCPtr);
    return ret;
  }

  public int GetSrcObjectCount(FbxCriteria pCriteria) {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetSrcObjectCount__SWIG_1(swigCPtr, FbxCriteria.getCPtr(pCriteria));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetSrcObject(int pIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetSrcObject__SWIG_0(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetSrcObject() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetSrcObject__SWIG_1(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetSrcObject(FbxCriteria pCriteria, int pIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetSrcObject__SWIG_2(swigCPtr, FbxCriteria.getCPtr(pCriteria), pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetSrcObject(FbxCriteria pCriteria) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetSrcObject__SWIG_3(swigCPtr, FbxCriteria.getCPtr(pCriteria));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject FindSrcObject(string pName, int pStartIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindSrcObject__SWIG_0(swigCPtr, pName, pStartIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject FindSrcObject(string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindSrcObject__SWIG_1(swigCPtr, pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject FindSrcObject(FbxCriteria pCriteria, string pName, int pStartIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindSrcObject__SWIG_2(swigCPtr, FbxCriteria.getCPtr(pCriteria), pName, pStartIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject FindSrcObject(FbxCriteria pCriteria, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindSrcObject__SWIG_3(swigCPtr, FbxCriteria.getCPtr(pCriteria), pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ConnectDstObject(FbxObject pObject, FbxConnection.EType pType) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ConnectDstObject__SWIG_0(swigCPtr, FbxObject.getCPtr(pObject), (int)pType);
    return ret;
  }

  public bool ConnectDstObject(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ConnectDstObject__SWIG_1(swigCPtr, FbxObject.getCPtr(pObject));
    return ret;
  }

  public bool IsConnectedDstObject(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsConnectedDstObject(swigCPtr, FbxObject.getCPtr(pObject));
    return ret;
  }

  public bool DisconnectDstObject(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectDstObject(swigCPtr, FbxObject.getCPtr(pObject));
    return ret;
  }

  public bool DisconnectAllDstObject() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectAllDstObject__SWIG_0(swigCPtr);
    return ret;
  }

  public bool DisconnectAllDstObject(FbxCriteria pCriteria) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectAllDstObject__SWIG_1(swigCPtr, FbxCriteria.getCPtr(pCriteria));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDstObjectCount() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetDstObjectCount__SWIG_0(swigCPtr);
    return ret;
  }

  public int GetDstObjectCount(FbxCriteria pCriteria) {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetDstObjectCount__SWIG_1(swigCPtr, FbxCriteria.getCPtr(pCriteria));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetDstObject(int pIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetDstObject__SWIG_0(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetDstObject() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetDstObject__SWIG_1(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetDstObject(FbxCriteria pCriteria, int pIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetDstObject__SWIG_2(swigCPtr, FbxCriteria.getCPtr(pCriteria), pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetDstObject(FbxCriteria pCriteria) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetDstObject__SWIG_3(swigCPtr, FbxCriteria.getCPtr(pCriteria));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject FindDstObject(string pName, int pStartIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindDstObject__SWIG_0(swigCPtr, pName, pStartIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject FindDstObject(string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindDstObject__SWIG_1(swigCPtr, pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject FindDstObject(FbxCriteria pCriteria, string pName, int pStartIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindDstObject__SWIG_2(swigCPtr, FbxCriteria.getCPtr(pCriteria), pName, pStartIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject FindDstObject(FbxCriteria pCriteria, string pName) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_FindDstObject__SWIG_3(swigCPtr, FbxCriteria.getCPtr(pCriteria), pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxProperty GetFirstProperty() {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetFirstProperty(swigCPtr), true);
    return ret;
  }

  public FbxProperty GetNextProperty(FbxProperty pProperty) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetNextProperty(swigCPtr, FbxProperty.getCPtr(pProperty)), true);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxProperty FindProperty(string pName, bool pCaseSensitive) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindProperty__SWIG_0(swigCPtr, pName, pCaseSensitive), true);
    return ret;
  }

  public FbxProperty FindProperty(string pName) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindProperty__SWIG_1(swigCPtr, pName), true);
    return ret;
  }

  public FbxProperty FindProperty(string pName, FbxDataType pDataType, bool pCaseSensitive) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindProperty__SWIG_2(swigCPtr, pName, FbxDataType.getCPtr(pDataType), pCaseSensitive), true);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxProperty FindProperty(string pName, FbxDataType pDataType) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindProperty__SWIG_3(swigCPtr, pName, FbxDataType.getCPtr(pDataType)), true);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxProperty FindPropertyHierarchical(string pName, bool pCaseSensitive) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindPropertyHierarchical__SWIG_0(swigCPtr, pName, pCaseSensitive), true);
    return ret;
  }

  public FbxProperty FindPropertyHierarchical(string pName) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindPropertyHierarchical__SWIG_1(swigCPtr, pName), true);
    return ret;
  }

  public FbxProperty FindPropertyHierarchical(string pName, FbxDataType pDataType, bool pCaseSensitive) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindPropertyHierarchical__SWIG_2(swigCPtr, pName, FbxDataType.getCPtr(pDataType), pCaseSensitive), true);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxProperty FindPropertyHierarchical(string pName, FbxDataType pDataType) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindPropertyHierarchical__SWIG_3(swigCPtr, pName, FbxDataType.getCPtr(pDataType)), true);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxProperty GetClassRootProperty() {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetClassRootProperty(swigCPtr), true);
    return ret;
  }

  public bool ConnectSrcProperty(FbxProperty pProperty) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ConnectSrcProperty(swigCPtr, FbxProperty.getCPtr(pProperty));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsConnectedSrcProperty(FbxProperty pProperty) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsConnectedSrcProperty(swigCPtr, FbxProperty.getCPtr(pProperty));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool DisconnectSrcProperty(FbxProperty pProperty) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectSrcProperty(swigCPtr, FbxProperty.getCPtr(pProperty));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetSrcPropertyCount() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetSrcPropertyCount(swigCPtr);
    return ret;
  }

  public FbxProperty GetSrcProperty(int pIndex) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetSrcProperty__SWIG_0(swigCPtr, pIndex), true);
    return ret;
  }

  public FbxProperty GetSrcProperty() {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetSrcProperty__SWIG_1(swigCPtr), true);
    return ret;
  }

  public FbxProperty FindSrcProperty(string pName, int pStartIndex) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindSrcProperty__SWIG_0(swigCPtr, pName, pStartIndex), true);
    return ret;
  }

  public FbxProperty FindSrcProperty(string pName) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindSrcProperty__SWIG_1(swigCPtr, pName), true);
    return ret;
  }

  public bool ConnectDstProperty(FbxProperty pProperty) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ConnectDstProperty(swigCPtr, FbxProperty.getCPtr(pProperty));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsConnectedDstProperty(FbxProperty pProperty) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsConnectedDstProperty(swigCPtr, FbxProperty.getCPtr(pProperty));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool DisconnectDstProperty(FbxProperty pProperty) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_DisconnectDstProperty(swigCPtr, FbxProperty.getCPtr(pProperty));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetDstPropertyCount() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetDstPropertyCount(swigCPtr);
    return ret;
  }

  public FbxProperty GetDstProperty(int pIndex) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetDstProperty__SWIG_0(swigCPtr, pIndex), true);
    return ret;
  }

  public FbxProperty GetDstProperty() {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_GetDstProperty__SWIG_1(swigCPtr), true);
    return ret;
  }

  public FbxProperty FindDstProperty(string pName, int pStartIndex) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindDstProperty__SWIG_0(swigCPtr, pName, pStartIndex), true);
    return ret;
  }

  public FbxProperty FindDstProperty(string pName) {
    FbxProperty ret = new FbxProperty(FbxWrapperNativePINVOKE.FbxObject_FindDstProperty__SWIG_1(swigCPtr, pName), true);
    return ret;
  }

  public int ContentUnload() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_ContentUnload(swigCPtr);
    return ret;
  }

  public int ContentLoad() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_ContentLoad(swigCPtr);
    return ret;
  }

  public bool ContentIsLoaded() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ContentIsLoaded(swigCPtr);
    return ret;
  }

  public void ContentDecrementLockCount() {
    FbxWrapperNativePINVOKE.FbxObject_ContentDecrementLockCount(swigCPtr);
  }

  public void ContentIncrementLockCount() {
    FbxWrapperNativePINVOKE.FbxObject_ContentIncrementLockCount(swigCPtr);
  }

  public bool ContentIsLocked() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ContentIsLocked(swigCPtr);
    return ret;
  }

  public virtual bool ContentWriteTo(FbxStream pStream) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ContentWriteTo(swigCPtr, FbxStream.getCPtr(pStream));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool ContentReadFrom(FbxStream pStream) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ContentReadFrom(swigCPtr, FbxStream.getCPtr(pStream));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void EmitMessage(SWIGTYPE_p_FbxMessage pMessage) {
    FbxWrapperNativePINVOKE.FbxObject_EmitMessage(swigCPtr, SWIGTYPE_p_FbxMessage.getCPtr(pMessage));
  }

  public virtual string Localize(string pID, string pDefault) {
    string ret = FbxWrapperNativePINVOKE.FbxObject_Localize__SWIG_0(swigCPtr, pID, pDefault);
    return ret;
  }

  public virtual string Localize(string pID) {
    string ret = FbxWrapperNativePINVOKE.FbxObject_Localize__SWIG_1(swigCPtr, pID);
    return ret;
  }

  public FbxLibrary GetParentLibrary() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetParentLibrary(swigCPtr);
    FbxLibrary ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLibrary(cPtr, false);
    return ret;
  }

  public bool AddImplementation(FbxImplementation pImplementation) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_AddImplementation(swigCPtr, FbxImplementation.getCPtr(pImplementation));
    return ret;
  }

  public bool RemoveImplementation(FbxImplementation pImplementation) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_RemoveImplementation(swigCPtr, FbxImplementation.getCPtr(pImplementation));
    return ret;
  }

  public bool HasDefaultImplementation() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_HasDefaultImplementation(swigCPtr);
    return ret;
  }

  public FbxImplementation GetDefaultImplementation() {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetDefaultImplementation(swigCPtr);
    FbxImplementation ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxImplementation(cPtr, false);
    return ret;
  }

  public bool SetDefaultImplementation(FbxImplementation pImplementation) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_SetDefaultImplementation(swigCPtr, FbxImplementation.getCPtr(pImplementation));
    return ret;
  }

  public int GetImplementationCount(FbxImplementationFilter pCriteria) {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetImplementationCount__SWIG_0(swigCPtr, FbxImplementationFilter.getCPtr(pCriteria));
    return ret;
  }

  public int GetImplementationCount() {
    int ret = FbxWrapperNativePINVOKE.FbxObject_GetImplementationCount__SWIG_1(swigCPtr);
    return ret;
  }

  public FbxImplementation GetImplementation(int pIndex, FbxImplementationFilter pCriteria) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetImplementation__SWIG_0(swigCPtr, pIndex, FbxImplementationFilter.getCPtr(pCriteria));
    FbxImplementation ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxImplementation(cPtr, false);
    return ret;
  }

  public FbxImplementation GetImplementation(int pIndex) {
    global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_GetImplementation__SWIG_1(swigCPtr, pIndex);
    FbxImplementation ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxImplementation(cPtr, false);
    return ret;
  }

  public virtual FbxString GetUrl() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxObject_GetUrl(swigCPtr), true);
    return ret;
  }

  public virtual bool SetUrl(string pUrl) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_SetUrl(swigCPtr, pUrl);
    return ret;
  }

  public void SetRuntimeClassId(FbxClassId pClassId) {
    FbxWrapperNativePINVOKE.FbxObject_SetRuntimeClassId(swigCPtr, FbxClassId.getCPtr(pClassId));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxClassId GetRuntimeClassId() {
    FbxClassId ret = new FbxClassId(FbxWrapperNativePINVOKE.FbxObject_GetRuntimeClassId(swigCPtr), true);
    return ret;
  }

  public bool IsRuntime(FbxClassId pClassId) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsRuntime(swigCPtr, FbxClassId.getCPtr(pClassId));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsRuntimePlug() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_IsRuntimePlug(swigCPtr);
    return ret;
  }

  public virtual void Compact() {
    FbxWrapperNativePINVOKE.FbxObject_Compact(swigCPtr);
  }

  public FbxProperty RootProperty {
    set {
      FbxWrapperNativePINVOKE.FbxObject_RootProperty_set(swigCPtr, FbxProperty.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = FbxWrapperNativePINVOKE.FbxObject_RootProperty_get(swigCPtr);
      FbxProperty ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxProperty(cPtr, false);
      return ret;
    } 
  }

  public virtual bool Compare(FbxObject pOtherObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_Compare(swigCPtr, FbxObject.getCPtr(pOtherObject));
    return ret;
  }

  public bool eq(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_eq(swigCPtr, FbxObject.getCPtr(pObject));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ne(FbxObject pObject) {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_ne(swigCPtr, FbxObject.getCPtr(pObject));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetDocument(FbxDocument pDocument) {
    FbxWrapperNativePINVOKE.FbxObject_SetDocument(swigCPtr, FbxDocument.getCPtr(pDocument));
  }

  public FbxPropertyHandle GetPropertyHandle() {
    FbxPropertyHandle ret = new FbxPropertyHandle(FbxWrapperNativePINVOKE.FbxObject_GetPropertyHandle(swigCPtr), false);
    return ret;
  }

  public virtual string GetTypeName() {
    string ret = FbxWrapperNativePINVOKE.FbxObject_GetTypeName(swigCPtr);
    return ret;
  }

  public virtual FbxStringList GetTypeFlags() {
    FbxStringList ret = new FbxStringList(FbxWrapperNativePINVOKE.FbxObject_GetTypeFlags(swigCPtr), true);
    return ret;
  }

  public void WipeAllConnections() {
    FbxWrapperNativePINVOKE.FbxObject_WipeAllConnections(swigCPtr);
  }

  public static void SetWipeMode(bool pState) {
    FbxWrapperNativePINVOKE.FbxObject_SetWipeMode(pState);
  }

  public static bool GetWipeMode() {
    bool ret = FbxWrapperNativePINVOKE.FbxObject_GetWipeMode();
    return ret;
  }

  public enum EObjectFlag {
    eNone = 0,
    eInitialized = 1 << 0,
    eSystem = 1 << 1,
    eSavable = 1 << 2,
    eSelected = 1 << 3,
    eHidden = 1 << 4,
    eContentLoaded = 1 << 5,
    eDontLocalize = 1 << 6,
    eCopyCalledByClone = 1 << 16
  }

  public enum ECloneType {
    eDeepClone,
    eReferenceClone
  }

}

}
