//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Internal.Fbx {

public class FbxString : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxString(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxString obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxString() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FbxWrapperNativePINVOKE.delete_FbxString(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxString() : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_0(), true) {
  }

  public FbxString(FbxString pString) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_1(FbxString.getCPtr(pString)), true) {
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxString(string pString) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_2(pString), true) {
  }

  public FbxString(char pChar, uint pNbRepeat) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_3(pChar, pNbRepeat), true) {
  }

  public FbxString(char pChar) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_4(pChar), true) {
  }

  public FbxString(string pCharPtr, uint pLength) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_5(pCharPtr, pLength), true) {
  }

  public FbxString(int pValue) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_6(pValue), true) {
  }

  public FbxString(float pValue) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_7(pValue), true) {
  }

  public FbxString(double pValue) : this(FbxWrapperNativePINVOKE.new_FbxString__SWIG_8(pValue), true) {
  }

  public uint GetLen() {
    uint ret = FbxWrapperNativePINVOKE.FbxString_GetLen(swigCPtr);
    return ret;
  }

  public uint Size() {
    uint ret = FbxWrapperNativePINVOKE.FbxString_Size(swigCPtr);
    return ret;
  }

  public bool IsEmpty() {
    bool ret = FbxWrapperNativePINVOKE.FbxString_IsEmpty(swigCPtr);
    return ret;
  }

  public FbxString Clear() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Clear(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_char at(int pIndex) {
    SWIGTYPE_p_char ret = new SWIGTYPE_p_char(FbxWrapperNativePINVOKE.FbxString_at__SWIG_0(swigCPtr, pIndex), false);
    return ret;
  }

  public string Buffer() {
    string ret = FbxWrapperNativePINVOKE.FbxString_Buffer__SWIG_0(swigCPtr);
    return ret;
  }

  public FbxString assign(FbxString pString) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_assign__SWIG_0(swigCPtr, FbxString.getCPtr(pString)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxString assign(char pChar) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_assign__SWIG_1(swigCPtr, pChar), false);
    return ret;
  }

  public FbxString assign(string pString) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_assign__SWIG_2(swigCPtr, pString), false);
    return ret;
  }

  public FbxString assign(int pValue) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_assign__SWIG_3(swigCPtr, pValue), false);
    return ret;
  }

  public FbxString assign(float pValue) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_assign__SWIG_4(swigCPtr, pValue), false);
    return ret;
  }

  public FbxString assign(double pValue) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_assign__SWIG_5(swigCPtr, pValue), false);
    return ret;
  }

  public FbxString add_assign(FbxString pString) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_add_assign__SWIG_0(swigCPtr, FbxString.getCPtr(pString)), false);
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxString add_assign(char pChar) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_add_assign__SWIG_1(swigCPtr, pChar), false);
    return ret;
  }

  public FbxString add_assign(string pString) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_add_assign__SWIG_2(swigCPtr, pString), false);
    return ret;
  }

  public FbxString add_assign(int pValue) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_add_assign__SWIG_3(swigCPtr, pValue), false);
    return ret;
  }

  public FbxString add_assign(float pValue) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_add_assign__SWIG_4(swigCPtr, pValue), false);
    return ret;
  }

  public FbxString add_assign(double pValue) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_add_assign__SWIG_5(swigCPtr, pValue), false);
    return ret;
  }

  public bool eq(FbxString pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_eq__SWIG_0(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ne(FbxString pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_ne__SWIG_0(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool lt(FbxString pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_lt__SWIG_0(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool lte(FbxString pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_lte__SWIG_0(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool gte(FbxString pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_gte__SWIG_0(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool gt(FbxString pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_gt__SWIG_0(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool eq(string pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_eq__SWIG_1(swigCPtr, pString);
    return ret;
  }

  public bool ne(string pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_ne__SWIG_1(swigCPtr, pString);
    return ret;
  }

  public bool lt(string pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_lt__SWIG_1(swigCPtr, pString);
    return ret;
  }

  public bool lte(string pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_lte__SWIG_1(swigCPtr, pString);
    return ret;
  }

  public bool gte(string pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_gte__SWIG_1(swigCPtr, pString);
    return ret;
  }

  public bool gt(string pString) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_gt__SWIG_1(swigCPtr, pString);
    return ret;
  }

  public string ToConstCharPtr() {
    string ret = FbxWrapperNativePINVOKE.FbxString_ToConstCharPtr(swigCPtr);
    return ret;
  }

  public FbxString Copy(string pString, uint pLength) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Copy(swigCPtr, pString, pLength), false);
    return ret;
  }

  public FbxString Append(string pString, uint pLength) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Append(swigCPtr, pString, pLength), false);
    return ret;
  }

  public int Compare(string pString) {
    int ret = FbxWrapperNativePINVOKE.FbxString_Compare(swigCPtr, pString);
    return ret;
  }

  public int CompareNoCase(string pString) {
    int ret = FbxWrapperNativePINVOKE.FbxString_CompareNoCase(swigCPtr, pString);
    return ret;
  }

  public void Swap(FbxString pString) {
    FbxWrapperNativePINVOKE.FbxString_Swap(swigCPtr, FbxString.getCPtr(pString));
    if (FbxWrapperNativePINVOKE.SWIGPendingException.Pending) throw FbxWrapperNativePINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxString Upper() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Upper(swigCPtr), true);
    return ret;
  }

  public FbxString Lower() {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Lower(swigCPtr), true);
    return ret;
  }

  public FbxString Mid(uint pFirst, uint pCount) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Mid__SWIG_0(swigCPtr, pFirst, pCount), true);
    return ret;
  }

  public FbxString Mid(uint pFirst) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Mid__SWIG_1(swigCPtr, pFirst), true);
    return ret;
  }

  public FbxString Left(uint pCount) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Left(swigCPtr, pCount), true);
    return ret;
  }

  public FbxString Right(uint pCount) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Right(swigCPtr, pCount), true);
    return ret;
  }

  public FbxString Pad(FbxString.EPaddingType pPadding, uint pLen, char pCar) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Pad__SWIG_0(swigCPtr, (int)pPadding, pLen, pCar), true);
    return ret;
  }

  public FbxString Pad(FbxString.EPaddingType pPadding, uint pLen) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_Pad__SWIG_1(swigCPtr, (int)pPadding, pLen), true);
    return ret;
  }

  public FbxString UnPad(FbxString.EPaddingType pPadding, char pCar) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_UnPad__SWIG_0(swigCPtr, (int)pPadding, pCar), true);
    return ret;
  }

  public FbxString UnPad(FbxString.EPaddingType pPadding) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_UnPad__SWIG_1(swigCPtr, (int)pPadding), true);
    return ret;
  }

  public int Find(char pChar, uint pStartPosition) {
    int ret = FbxWrapperNativePINVOKE.FbxString_Find__SWIG_0(swigCPtr, pChar, pStartPosition);
    return ret;
  }

  public int Find(char pChar) {
    int ret = FbxWrapperNativePINVOKE.FbxString_Find__SWIG_1(swigCPtr, pChar);
    return ret;
  }

  public int Find(string pStrSub, uint pStartPosition) {
    int ret = FbxWrapperNativePINVOKE.FbxString_Find__SWIG_2(swigCPtr, pStrSub, pStartPosition);
    return ret;
  }

  public int Find(string pStrSub) {
    int ret = FbxWrapperNativePINVOKE.FbxString_Find__SWIG_3(swigCPtr, pStrSub);
    return ret;
  }

  public int ReverseFind(char pChar) {
    int ret = FbxWrapperNativePINVOKE.FbxString_ReverseFind(swigCPtr, pChar);
    return ret;
  }

  public int FindOneOf(string pStrCharSet, uint pStartPosition) {
    int ret = FbxWrapperNativePINVOKE.FbxString_FindOneOf__SWIG_0(swigCPtr, pStrCharSet, pStartPosition);
    return ret;
  }

  public int FindOneOf(string pStrCharSet) {
    int ret = FbxWrapperNativePINVOKE.FbxString_FindOneOf__SWIG_1(swigCPtr, pStrCharSet);
    return ret;
  }

  public bool FindAndReplace(string pFind, string pReplaceBy, uint pStartPosition) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_FindAndReplace__SWIG_0(swigCPtr, pFind, pReplaceBy, pStartPosition);
    return ret;
  }

  public bool FindAndReplace(string pFind, string pReplaceBy) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_FindAndReplace__SWIG_1(swigCPtr, pFind, pReplaceBy);
    return ret;
  }

  public bool ReplaceAll(string pFind, string pReplaceBy) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_ReplaceAll__SWIG_0(swigCPtr, pFind, pReplaceBy);
    return ret;
  }

  public bool ReplaceAll(char pFind, char pReplaceBy) {
    bool ret = FbxWrapperNativePINVOKE.FbxString_ReplaceAll__SWIG_1(swigCPtr, pFind, pReplaceBy);
    return ret;
  }

  public int GetTokenCount(string pSpans) {
    int ret = FbxWrapperNativePINVOKE.FbxString_GetTokenCount(swigCPtr, pSpans);
    return ret;
  }

  public FbxString GetToken(int pTokenIndex, string pSpans) {
    FbxString ret = new FbxString(FbxWrapperNativePINVOKE.FbxString_GetToken(swigCPtr, pTokenIndex, pSpans), true);
    return ret;
  }

  public enum EPaddingType {
    eRight,
    eLeft,
    eBoth
  }

}

}
